name: riverpod_clean
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  auto_route: ^9.2.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  google_fonts: ^6.2.1
  hooks_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.12
  custom_lint: ^0.6.4
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.2
  riverpod_lint: ^2.3.12

flutter:
  uses-material-design: true
